"use strict";

var pathUtil = require('path'),
    fs = require("fs"),
    pathHelpers = require("../../shared/helpers/pathHelpers.js"),
    config = require("../../shared/config.js"),
    paths = config.paths;

var pathPrefix = '/app/pages/';

/**
 * Check if a requested page exists on the file-system
 * This function is used to reject all requests that are not mapped with a page
 *
 * The check does not take care of the files generated by the "bundle".
 * The check looks only at the source files at /app/pages/<YourAppFolder>
 * @param {!String} pageName
 * @param {Function} callback
 */
function checkPageExists(pageName, callback) {

    if (pageName.indexOf(pathPrefix) !== 0) {
        pageName = pathPrefix + pageName.substr(1);     // remove leading slash
    }

    //sanitize first
    pageName = pathHelpers.apply.modifier(
        pathHelpers.modifiers.normalize,
        pathHelpers.modifiers.noTrailingSlash
    ).on(pageName);

    pageName = paths.root + pageName;

    fs.stat(pageName, function(err, stats) {

        if(err) {
            callback(false);
            return;
        }

        callback(stats.isDirectory());
    });
}

module.exports = checkPageExists;